Switch to using the fnnas kernel to package the image

diff --git a/renas b/renas
--- a/renas
+++ b/renas
@@ -83,23 +83,11 @@ uboot_repo="https://github.com/ophub/u-boot"
 firmware_repo="https://github.com/ophub/firmware"
 
 # Set the kernel download repository from github.com
-kernel_repo="https://github.com/ophub/kernel"
-# Set the tags(kernel_xxx) of the default kernel that can be replaced via the [ -u ] parameter
-default_tags="stable"
-kernel_usage=""
+kernel_repo="https://github.com/ophub/fnnas"
 # Set the list of kernels used by default(Selectable version)
 stable_kernel=("6.12.y")
-flippy_kernel=(${stable_kernel[@]})
-beta_kernel=(${stable_kernel[@]})
-rk3588_kernel=("6.1.y")
-rk35xx_kernel=("6.1.y")
-h6_kernel=("6.6.y")
-specific_6xy=("6.1.y" "6.6.y" "6.12.y")
-specific_5xy=("5.10.y" "5.15.y")
 # Set to automatically use the latest kernel
 auto_kernel="true"
-# Initialize the kernel array
-declare -A tags_list
 
 # Set the Amlogic's u-boot series(u-boot-xxx.bin)
 uboot_meson_gxl=("p201.bin" "p212.bin" "s905x-s912.bin" "n1.bin" "r3300l.bin")
@@ -178,7 +166,7 @@ init_var() {
     echo -e "${STEPS} Start Initializing Variables..."
 
     # If it is followed by [ : ], it means that the option requires a parameter value
-    local options="b:r:u:k:a:p:s:n:"
+    local options="b:r:k:a:p:s:n:"
     parsed_args=$(getopt -o "${options}" -- "${@}")
     [[ ${?} -ne 0 ]] && error_msg "Parameter parsing failed."
     eval set -- "${parsed_args}"
@@ -201,22 +189,11 @@ init_var() {
                 error_msg "Invalid -r parameter [ ${2} ]!"
             fi
             ;;
-        -u | --kernelUsage)
-            if [[ -n "${2}" ]]; then
-                kernel_usage="${2//kernel_/}"
-                shift 2
-            else
-                error_msg "Invalid -u parameter [ ${2} ]!"
-            fi
-            ;;
         -k | --Kernel)
             if [[ -n "${2}" ]]; then
                 oldIFS="${IFS}"
                 IFS="_"
                 stable_kernel=(${2})
-                flippy_kernel=(${2})
-                beta_kernel=(${2})
-                specific_kernel=(${2})
                 IFS="${oldIFS}"
                 shift 2
             else
@@ -306,71 +283,14 @@ check_data() {
         board_list=":($(echo ${make_fnnas[@]} | sed -e 's/ /\|/g')):(yes|no)"
     }
 
-    # Get the kernel array
+    # Get the kernel array(amlogic/rockchip/allwinner) from the model configuration file
     kernel_from=($(
         cat ${model_conf} |
             sed -e 's/NA//g' -e 's/NULL//g' -e 's/[ ][ ]*//g' |
-            grep -E "^[^#].*${board_list}$" | awk -F':' '{print $9}' |
+            grep -E "^[^#].*${board_list}$" | awk -F':' '{print $10}' |
             sort -u | xargs
     ))
-    [[ "${#kernel_from[@]}" -eq 0 ]] && error_msg "Missing [ KERNEL_TAGS ] settings, stop building."
-    # Replace custom kernel tags
-    [[ -n "${kernel_usage}" ]] && {
-        for ((i = 0; i < ${#kernel_from[@]}; i++)); do
-            if [[ ${kernel_from[${i}]} == "${default_tags}/"* ]]; then
-                kernel_from[${i}]="${kernel_from[${i}]//${default_tags}/${kernel_usage}}"
-            fi
-        done
-    }
-
-    # Convert the kernel_from to the kernel array
-    for item in "${kernel_from[@]}"; do
-        # Split the key and value
-        IFS='/' read -r key value <<<"${item}"
-
-        # Check if the value is "all".
-        if [[ "${value}" == "all" ]]; then
-            # If the value is "all", assign the value of ${key}_kernel. such as [ stable_kernel, rk3588_kernel, etc. ]
-            eval "value=\"\${${key}_kernel[@]}\""
-        elif [[ "${value}" =~ ^[1-9]+ ]]; then
-            if [[ "${value}" == "5.x.y" ]]; then
-                value="${specific_5xy[@]}"
-            elif [[ "${value}" == "6.x.y" ]]; then
-                value="${specific_6xy[@]}"
-            else
-                IFS='_' read -ra value <<<"${value}"
-                value="${value[@]}"
-            fi
-        fi
-
-        # If auto_kernel is false, use the value from -k parameter
-        if [[ ! "${auto_kernel}" =~ ^(true|yes)$ ]]; then
-            if [[ "${#specific_kernel[@]}" -eq 0 ]]; then
-                error_msg "Plase use the -k parameter to specify the kernel version."
-            else
-                value="${specific_kernel[@]}"
-            fi
-        fi
-
-        # Merge the same key values
-        if [[ -n "${tags_list[${key}]}" ]]; then
-            tags_list[${key}]+=" ${value}"
-        else
-            tags_list[${key}]="${value}"
-        fi
-    done
-
-    # Convert the tags_list array to the kernel array (remove duplicates)
-    for key in "${!tags_list[@]}"; do
-        # Convert the space-separated string to an array and remove duplicates
-        read -ra unique_values <<<"$(echo "${tags_list[${key}]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')"
-        # Assign the unique values back to the tags_list
-        tags_list[${key}]="${unique_values[@]}"
-    done
-
-    # Check the kernel tags list
-    [[ "${#tags_list[@]}" -eq 0 ]] && error_msg "The [ tags_list ] is missing, stop building."
-    echo -e "${INFO} The kernel tags list: [ ${!tags_list[@]} ]"
+    [[ "${#kernel_from[@]}" -eq 0 ]] && error_msg "Missing [ PLATFORM ] settings, stop building."
 
     # Convert kernel repository address to api format
     [[ "${kernel_repo}" =~ ^https: ]] && kernel_repo="$(echo ${kernel_repo} | awk -F'/' '{print $4"/"$5}')"
@@ -456,105 +376,72 @@ query_kernel() {
     echo -e "${STEPS} Start querying the latest kernel version..."
 
     # Check the version on the kernel repository
-    x="1"
-    for key in "${!tags_list[@]}"; do
-        {
-            # Query the name of the latest kernel version
-            tmp_arr_kernels=()
-            down_kernel_list=(${tags_list[${key}]})
-            i=1
-            for kernel_var in "${down_kernel_list[@]}"; do
-                echo -e "${INFO} (${x}.${i}) Auto query the latest kernel version for [ ${key} - ${kernel_var} ]"
+    tmp_arr_kernels=()
+    i=1
+    for kernel_var in "${stable_kernel[@]}"; do
+        echo -e "${INFO} (${i}) Auto query the latest kernel version for [ ${kernel_var} ]"
 
-                # Identify the kernel <VERSION> and <PATCHLEVEL>, such as [ 6.1 ]
-                kernel_verpatch="$(echo ${kernel_var} | awk -F '.' '{print $1"."$2}')"
+        # Identify the kernel <VERSION> and <PATCHLEVEL>, such as [ 6.1 ]
+        kernel_verpatch="$(echo ${kernel_var} | awk -F '.' '{print $1"."$2}')"
 
-                # Query the latest kernel version
-                latest_version="$(
-                    curl -fsSL \
-                        ${kernel_api}/releases/expanded_assets/kernel_${key} |
-                        grep -oE "${kernel_verpatch}\.[0-9]+\.tar\.gz" | sed 's/.tar.gz//' |
-                        sort -urV | head -n 1
-                )"
+        # Query the latest kernel version
+        latest_version="$(
+            curl -fsSL \
+                ${kernel_api}/releases/expanded_assets/kernel_fnnas |
+                grep -oE "${kernel_verpatch}\.[0-9]+(-[a-zA-Z0-9]+)?\.tar\.gz" |
+                sed -E 's/(-[a-zA-Z0-9]+)?\.tar\.gz//' |
+                sort -urV | head -n 1
+        )"
 
-                if [[ "${?}" -eq 0 && -n "${latest_version}" ]]; then
-                    tmp_arr_kernels[${i}]="${latest_version}"
-                else
-                    tmp_arr_kernels[${i}]="${kernel_var}"
-                fi
+        if [[ "${?}" -eq 0 && -n "${latest_version}" ]]; then
+            tmp_arr_kernels[${i}]="${latest_version}"
+        else
+            tmp_arr_kernels[${i}]="${kernel_var}"
+        fi
 
-                echo -e "${INFO} (${x}.${i}) [ ${key} - ${tmp_arr_kernels[$i]} ] is latest kernel. \n"
+        echo -e "${INFO} (${i}) [ ${tmp_arr_kernels[$i]} ] is latest kernel. \n"
 
-                ((i++))
-            done
-
-            # Assign the latest kernel version to the array
-            tags_list[${key}]="${tmp_arr_kernels[@]}"
-
-            ((x++))
-        }
+        ((i++))
     done
-}
 
-check_kernel() {
-    [[ -n "${1}" ]] && check_path="${1}" || error_msg "Invalid kernel path to check."
-    check_files=($(cat "${check_path}/sha256sums" | awk '{print $2}'))
-    for cf in "${check_files[@]}"; do
-        {
-            # Check if file exists
-            [[ -s "${check_path}/${cf}" ]] || error_msg "The [ ${cf} ] file is missing."
-            # Check if the file sha256sum is correct
-            tmp_sha256sum="$(sha256sum "${check_path}/${cf}" | awk '{print $1}')"
-            tmp_checkcode="$(cat ${check_path}/sha256sums | grep ${cf} | awk '{print $1}')"
-            [[ "${tmp_sha256sum}" == "${tmp_checkcode}" ]] || error_msg "[ ${cf} ]: sha256sum verification failed."
-        }
-    done
-    echo -e "${INFO} All [ ${#check_files[@]} ] kernel files are sha256sum checked to be complete.\n"
+    # Set the latest kernel array
+    stable_kernel=("${tmp_arr_kernels[@]}")
 }
 
 download_kernel() {
     cd ${current_path}
     echo -e "${STEPS} Start downloading the kernel files..."
 
-    x="1"
-    for key in "${!tags_list[@]}"; do
-        {
-            down_kernel_list=(${tags_list[${key}]})
-            # Download the kernel to the storage directory
-            i="1"
-            for kernel_var in "${down_kernel_list[@]}"; do
-                if [[ ! -d "${kernel_path}/${key}/${kernel_var}" ]]; then
-                    kernel_down_from="https://github.com/${kernel_repo}/releases/download/kernel_${key}/${kernel_var}.tar.gz"
-                    echo -e "${INFO} (${x}.${i}) [ ${key} - ${kernel_var} ] Kernel download from [ ${kernel_down_from} ]"
+    # Download the kernel to the storage directory
+    i="1"
+    for kernel_var in "${stable_kernel[@]}"; do
+        for key in "${kernel_from[@]}"; do
+            kernel_down_from="https://github.com/${kernel_repo}/releases/download/kernel_fnnas/${kernel_var}-${key}.tar.gz"
 
-                    # Download the kernel files. If the download fails, try again 10 times.
-                    [[ -d "${kernel_path}/${key}" ]] || mkdir -p ${kernel_path}/${key}
-                    for t in {1..10}; do
-                        curl -fsSL "${kernel_down_from}" -o "${kernel_path}/${key}/${kernel_var}.tar.gz"
-                        [[ "${?}" -eq 0 ]] && break || sleep 60
-                    done
-                    [[ "${?}" -eq 0 ]] || error_msg "Failed to download the kernel files from the server."
+            # Download the kernel files. If the download fails, try again 10 times.
+            if [[ ! -d "${kernel_path}/${kernel_var}/${kernel_var}-${key}" ]]; then
+                echo -e "${INFO} (${i}) [ ${kernel_var} - ${key} ] Kernel download from [ ${kernel_down_from} ]"
+                mkdir -p "${kernel_path}/${kernel_var}"
+                for t in {1..10}; do
+                    curl -fsSL "${kernel_down_from}" -o "${kernel_path}/${kernel_var}/${kernel_var}-${key}.tar.gz"
+                    [[ "${?}" -eq 0 ]] && break || sleep 60
+                done
+                [[ "${?}" -eq 0 ]] || error_msg "Failed to download the kernel files from the server."
 
-                    # Decompress the kernel files
-                    tar -mxzf "${kernel_path}/${key}/${kernel_var}.tar.gz" -C "${kernel_path}/${key}"
-                    [[ "${?}" -eq 0 ]] || error_msg "[ ${kernel_var} ] kernel decompression failed."
-                else
-                    echo -e "${INFO} (${x}.${i}) [ ${key} - ${kernel_var} ] Kernel is in the local directory."
-                fi
+                # Decompress the kernel files
+                tar -mxzf "${kernel_path}/${kernel_var}/${kernel_var}-${key}.tar.gz" -C "${kernel_path}/${kernel_var}"
+                [[ "${?}" -eq 0 ]] || error_msg "[ ${kernel_var} ] kernel decompression failed."
+            else
+                echo -e "${INFO} (${i}) [ ${kernel_var} - ${key} ] Kernel file already exists, skip download."
+            fi
+        done
 
-                # If the kernel contains the sha256sums file, check the files integrity
-                [[ -f "${kernel_path}/${key}/${kernel_var}/sha256sums" ]] && check_kernel "${kernel_path}/${key}/${kernel_var}"
-
-                ((i++))
-            done
-
-            # Delete downloaded kernel temporary files
-            rm -f ${kernel_path}/${key}/*.tar.gz
-            sync
-
-            ((x++))
-        }
+        ((i++))
     done
+
+    # Delete downloaded kernel temporary files
+    rm -f ${kernel_path}/${kernel_var}/*.tar.gz
+    sync
 }
 
 confirm_version() {
@@ -602,39 +489,6 @@ confirm_version() {
     # Set the Amlogic u-boot series
     family_rename="${FAMILY//-/_}"
     eval "amlogic_uboot=(\${uboot_${family_rename}[@]})"
-
-    # Get the kernel tags and version
-    conf_kernel_tags="${KERNEL_TAGS%%/*}"
-    conf_kernel_list="${KERNEL_TAGS##*/}"
-    # Replace the default kernel tags with the custom kernel tags
-    [[ -n "${kernel_usage}" && "${conf_kernel_tags}" == "${default_tags}" ]] && conf_kernel_tags="${kernel_usage}"
-    # Check the kernel tags and version
-    [[ -z "${conf_kernel_tags}" ]] && error_msg "The [ ${KERNEL_TAGS} ] is missing tags part."
-    [[ -z "${conf_kernel_list}" ]] && error_msg "The [ ${KERNEL_TAGS} ] is missing list part."
-
-    # Find the kernel list defined in the model database
-    model_kernel=()
-    if [[ "${conf_kernel_list}" == "all" ]]; then
-        eval "model_kernel=(\"\${${conf_kernel_tags}_kernel[@]}\")"
-        model_kernel=($(echo "${model_kernel[@]}" | xargs -n1 | sed -E 's/^([0-9]+\.[0-9]+)(\.[a-z0-9]+)?$/\1.[0-9]+/'))
-    else
-        # Convert the string into an array, using "_" as the delimiter
-        IFS='_' read -ra conf_kernel_list <<<"${conf_kernel_list}"
-        model_kernel=($(echo "${conf_kernel_list[@]}" | xargs -n1 | sed -E 's/^([0-9]+\.[0-9]+)(\.[a-z0-9]+)?$/\1.[0-9]+/'))
-    fi
-    # Check the kernel list
-    [[ "${#model_kernel[@]}" -eq 0 ]] && error_msg "The kernel list is empty for [ ${board} ]"
-
-    # Find the kernel version that matches the custom version
-    build_kernel=()
-    latest_kernel=(${tags_list[${conf_kernel_tags}]})
-    for ck in "${model_kernel[@]}"; do
-        for lk in "${latest_kernel[@]}"; do
-            [[ "${lk}" =~ ^${ck}$ ]] && build_kernel+=("${lk}")
-        done
-    done
-    # Check the kernel version
-    [[ "${#build_kernel[@]}" -eq 0 ]] && error_msg "The kernel list is invalid for [ ${board} ]"
 }
 
 extract_fnnas() {
@@ -855,12 +709,14 @@ replace_kernel() {
     cd ${current_path}
 
     # Determine custom kernel filename
-    kernel_boot="$(ls ${kernel_path}/${conf_kernel_tags}/${kernel}/boot-${kernel}*.tar.gz 2>/dev/null | head -n 1)"
-    kernel_name="${kernel_boot##*/}" && kernel_name="${kernel_name:5:-7}"
+    kernel_boot="$(ls ${kernel_path}/${kernel}/${kernel}-${PLATFORM}/boot-${PLATFORM}-${kernel}*.tar.gz 2>/dev/null | head -n 1)"
+    kernel_name="${kernel_boot##*/}"
+    kernel_name="${kernel_name#boot-${PLATFORM}-}"
+    kernel_name="${kernel_name%.tar.gz}"
     [[ -n "${kernel_name}" ]] || error_msg "Missing kernel files for [ ${kernel} ]"
-    kernel_dtb="${kernel_path}/${conf_kernel_tags}/${kernel}/dtb-${PLATFORM}-${kernel_name}.tar.gz"
-    kernel_modules="${kernel_path}/${conf_kernel_tags}/${kernel}/modules-${kernel_name}.tar.gz"
-    kernel_header="${kernel_path}/${conf_kernel_tags}/${kernel}/header-${kernel_name}.tar.gz"
+    kernel_dtb="${kernel_path}/${kernel}/${kernel}-${PLATFORM}/dtb-${PLATFORM}-${kernel_name}.tar.gz"
+    kernel_modules="${kernel_path}/${kernel}/${kernel}-${PLATFORM}/modules-${PLATFORM}-${kernel_name}.tar.gz"
+    kernel_header="${kernel_path}/${kernel}/${kernel}-${PLATFORM}/header-${PLATFORM}-${kernel_name}.tar.gz"
     [[ -s "${kernel_boot}" && -s "${kernel_dtb}" && -s "${kernel_modules}" && -s "${kernel_header}" ]] || error_msg "The 4 kernel missing."
 
     # 01. For /boot five files
@@ -886,7 +742,7 @@ replace_kernel() {
     # 04. For /usr/lib/modules/${kernel_name}
     tar -mxzf ${kernel_modules} -C ${tag_rootfs}/usr/lib/modules
     (cd ${tag_rootfs}/usr/lib/modules/${kernel_name}/ && rm -f build source 2>/dev/null && ln -sf /usr/src/${header_path} build)
-    [[ "$(ls ${tag_rootfs}/usr/lib/modules/${kernel_name} -l 2>/dev/null | grep "^d" | wc -l)" -eq "1" ]] || error_msg "/usr/lib/modules kernel folder is missing."
+    [[ "$(ls ${tag_rootfs}/usr/lib/modules/${kernel_name} -l 2>/dev/null | grep "^d" | wc -l)" -ge "1" ]] || error_msg "/usr/lib/modules kernel folder is missing."
 
     # Special procedures for flashing specific boards
     [[ "${adjust_kernel_files}" == "yes" ]] && adjust_kernel_files_cmd
@@ -1043,7 +899,7 @@ refactor_rootfs() {
     echo "FAMILY='${FAMILY}'" >>${ophub_release_file}
     echo "BOARD='${board}'" >>${ophub_release_file}
     echo "KERNEL_REPO='${kernel_repo}'" >>${ophub_release_file}
-    echo "KERNEL_TAGS='${conf_kernel_tags}'" >>${ophub_release_file}
+    echo "KERNEL_TAGS='kernel_fnnas'" >>${ophub_release_file}
     echo "KERNEL_VERSION='${kernel}'" >>${ophub_release_file}
     echo "KERNEL_BACKUP='yes'" >>${ophub_release_file}
     echo "BOOT_CONF='${BOOT_CONF}'" >>${ophub_release_file}
@@ -1102,13 +958,13 @@ loop_make() {
             confirm_version
 
             i="1"
-            for k in "${build_kernel[@]}"; do
+            for k in "${stable_kernel[@]}"; do
                 {
                     # Set the kernel version
                     kernel="${k}"
 
                     # Check disk space size
-                    echo -ne "(${j}.${i}) Start making fnnas [\033[92m ${board} - ${conf_kernel_tags}/${kernel} \033[0m]. "
+                    echo -ne "(${j}.${i}) Start making fnnas [\033[92m ${board} - ${kernel} \033[0m]. "
                     now_remaining_space="$(df -Tk ${make_path} | tail -n1 | awk '{print $5}' | echo $(($(xargs) / 1024 / 1024)))"
                     if [[ "${now_remaining_space}" -le "10" ]]; then
                         echo -e "${WARNING} Remaining space is less than 10G, exit this make."
@@ -1156,7 +1012,7 @@ download_kernel
 
 # Show make settings
 echo -e "${INFO} [ ${#make_fnnas[@]} ] lists of fnnas board: [ $(echo ${make_fnnas[@]} | xargs) ]"
-echo -e "${INFO} Kernel Repo: [ ${kernel_repo} ], Kernel Usage: [ ${kernel_usage} ] \n"
+echo -e "${INFO} Kernel Repo: [ ${kernel_repo} ], Kernel from: [ $(echo ${kernel_from[@]} | xargs) ] \n"
 # Show server start information
 echo -e "${INFO} Server space usage before starting to compile: \n$(df -hT ${make_path}) \n"
 
